---
- name: configuring router
  hosts: Routers
  connection: ansible.netcommon.network_cli
  gather_facts: false
  vars_files:
   - vars.yml
  tasks:
    - ansible.builtin.debug:
        msg: task1
    - import_tasks: tasks.yml
    
