---
- name: configuring router
  hosts: Routers
  gather_facts: false
  tasks:
    - ansible.builtin.debug:
        msg: initial config for routers
    - include_vars:  
        file: vars.yml
    - name: sending config commands
      cisco.ios.ios_config: 
        src: commands.j2
    
