---
- name: configuring router
  hosts: Routers
  gather_facts: false
  tasks:
    - name: sending config commands
      cisco.ios.ios_config: 
        src: '{{ inventory_hostname }}.j2'
        save_when: always
